# Generated by Django 4.0.4 on 2022-05-15 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_bookborrow_return_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookborrow',
            name='book_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='app.book'),
            preserve_default=False,
        ),
    ]
