# Generated by Django 4.0.4 on 2022-05-17 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=10, unique=True)),
                ('fullname', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100, null=True)),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
    ]
